services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-app_db_test}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    # Copy init.sql content directly via environment or use tmpfs
    command: >
      bash -c "
      echo 'CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL UNIQUE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
      INSERT INTO users (name, email) VALUES
        (\"Alice Johnson\", \"alice@example.com\"),
        (\"Bob Smith\", \"bob@example.com\"),
        (\"Charlie Brown\", \"charlie@example.com\");' > /docker-entrypoint-initdb.d/init.sql &&
      exec docker-entrypoint.sh mysqld
      "
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD:-rootpassword}"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - app-network

  api:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-rootpassword}
      DB_NAME: ${DB_NAME:-app_db_test}
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
